# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\nxencoder\resources\ui_about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(461, 221)
        About.setMinimumSize(QtCore.QSize(461, 221))
        About.setMaximumSize(QtCore.QSize(461, 221))
        self.svg_widget = QSvgWidget(About)
        self.svg_widget.setGeometry(QtCore.QRect(-10, -5, 131, 131))
        self.svg_widget.setObjectName("svg_widget")
        self.btn_close = QtWidgets.QPushButton(About)
        self.btn_close.setGeometry(QtCore.QRect(380, 190, 75, 23))
        self.btn_close.setObjectName("btn_close")
        self.lbl_title = QtWidgets.QLabel(About)
        self.lbl_title.setGeometry(QtCore.QRect(115, 10, 341, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.lbl_version = QtWidgets.QLabel(About)
        self.lbl_version.setGeometry(QtCore.QRect(115, 25, 61, 16))
        self.lbl_version.setObjectName("lbl_version")
        self.lbl_about = QtWidgets.QLabel(About)
        self.lbl_about.setGeometry(QtCore.QRect(115, 80, 341, 41))
        self.lbl_about.setWordWrap(True)
        self.lbl_about.setObjectName("lbl_about")
        self.lbl_author = QtWidgets.QLabel(About)
        self.lbl_author.setGeometry(QtCore.QRect(115, 40, 341, 16))
        self.lbl_author.setObjectName("lbl_author")
        self.lbl_license = QtWidgets.QLabel(About)
        self.lbl_license.setGeometry(QtCore.QRect(115, 55, 341, 16))
        self.lbl_license.setObjectName("lbl_license")
        self.btn_github = QtWidgets.QPushButton(About)
        self.btn_github.setGeometry(QtCore.QRect(10, 190, 81, 23))
        self.btn_github.setObjectName("btn_github")
        self.lbl_credits = QtWidgets.QLabel(About)
        self.lbl_credits.setGeometry(QtCore.QRect(10, 130, 441, 61))
        self.lbl_credits.setWordWrap(True)
        self.lbl_credits.setObjectName("lbl_credits")
        self.btn_ratrig = QtWidgets.QPushButton(About)
        self.btn_ratrig.setGeometry(QtCore.QRect(100, 190, 81, 23))
        self.btn_ratrig.setObjectName("btn_ratrig")
        self.btn_ratrig_community = QtWidgets.QPushButton(About)
        self.btn_ratrig_community.setGeometry(QtCore.QRect(190, 190, 141, 23))
        self.btn_ratrig_community.setObjectName("btn_ratrig_community")

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About nxEncoder Utility"))
        self.btn_close.setText(_translate("About", "Close"))
        self.lbl_title.setText(_translate("About", "About nxEncoder Utility"))
        self.lbl_version.setText(_translate("About", "Version x.x"))
        self.lbl_about.setText(_translate("About", "nxEncoder Utility is a companion application to the open-source filament encoder design by Simon Davie. It allows fast and accurate calibration of multiple aspects of a FDM 3D printer extrusion system."))
        self.lbl_author.setText(_translate("About", "Designed and written by Simon Davie <nexx@nexxdesign.co.uk>"))
        self.lbl_license.setText(_translate("About", "Open source, released under the GNU General Public License v3.0"))
        self.btn_github.setText(_translate("About", "GitHub.com"))
        self.lbl_credits.setText(_translate("About", "Many thanks to both RatRig©, and the members of the RatRig© community group, for their advice, ideas, testing and continued support.\n"
"\n"
"Icon created by Good Ware (https://www.flaticon.com/authors/good-ware)\n"
""))
        self.btn_ratrig.setText(_translate("About", "RatRig.com"))
        self.btn_ratrig_community.setText(_translate("About", "RatRig Community Group"))
from PyQt5.QtSvg import QSvgWidget
